# Author : Alxhr0
# The theme uses the Biscuit pallete from : github.com/tsukki9696/biscuit

"attribute" = "fg0"
"keyword" = { fg = "purple1" }
"keyword.directive" = "blue0"
"namespace" = "fg0"
"punctuation" = "fg0"
"punctuation.delimiter" = "fg0"
"operator" = "purple1"
"special" = "purple0"
"variable.other.member" = "blue1"
"variable" = "fg1"
"variable.builtin" = "fg0"
"variable.parameter" = "fg2"
"type" = "yellow1"
"type.builtin" = "yellow1"
"constructor" = { fg = "purple1", modifiers = ["bold"] }
"function" = { fg = "blue1", modifiers = ["bold"] }
"function.macro" = "aqua1"
"function.builtin" = "yellow1"
"tag" = "red1"
"comment" = { fg = "gray1", modifiers = ["italic"]  }
"constant" = { fg = "purple1" }
"constant.builtin" = { fg = "purple1", modifiers = ["bold"] }
"string" = "green1"
"constant.numeric" = "purple1"
"constant.character.escape" = { fg = "fg2", modifiers = ["bold"] }
"label" = "aqua1"
"module" = "aqua1"

"diff.plus" = "green1"
"diff.delta" = "orange1"
"diff.minus" = "red1"

"warning" = "orange1"
"error" = "red1"
"info" = "aqua1"
"hint" = "blue1"

"ui.background" = {}
"ui.linenr" = { fg = "bg4" }
"ui.linenr.selected" = { fg = "yellow1" }
"ui.cursorline" = { bg = "bg1" }
"ui.statusline" = { fg = "fg1", bg = "bg1" }
"ui.statusline.normal" = { fg = "fg1", bg = "bg1" }
"ui.statusline.insert" = { fg = "fg1", bg = "blue0" }
"ui.statusline.select" = { fg = "fg1", bg = "orange0" }
"ui.statusline.inactive" = { fg = "fg4", bg = "bg1" }
"ui.popup" = { bg = "bg1" }
"ui.window" = { bg = "bg1" }
"ui.help" = { fg = "fg1" }
"ui.text" = { fg = "fg1" }
"ui.text.focus" = { fg = "fg1" }
"ui.selection" = { bg = "bg2" }
"ui.selection.primary" = { bg = "bg3" }
"ui.cursor.primary" = { bg = "fg4", fg = "bg1" }
"ui.cursor.match" = { bg = "bg3" }
"ui.menu" = { fg = "fg1", bg = "bg1" }
"ui.menu.selected" = { fg = "bg1", bg = "cyan", modifiers = ["bold"] }
"ui.virtual.whitespace" = "bg2"
"ui.virtual.ruler" = { bg = "bg1" }
"ui.virtual.inlay-hint" = { fg = "gray1" }

"diagnostic.warning" = { underline = { color = "orange1", style = "curl" } }
"diagnostic.error" = { underline = { color = "red1", style = "curl" } }
"diagnostic.info" = { underline = { color = "aqua1", style = "curl" } }
"diagnostic.hint" = { underline = { color = "blue1", style = "curl" } }

"markup.heading" = "aqua1"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "green1", modifiers = ["underlined"] }
"markup.link.text" = "red1"
"markup.raw" = "red1"

[palette]
bg0 = "#fff7eb" # main background
bg1 = "#d6cfc5"
bg2 = "#ccc6bc"
bg3 = "#c2bcb3"
bg4 = "#e8e1d6"

fg0 = "#3d3131"
fg1 = "#2d2424" # main foreground
fg2 = "#241d1d"
fg3 = "#1a1515"
fg4 = "#9d9891" # gray0

gray0 = "#585151"
gray1 = "#4d4646"

red0 = "#B54851" # neutral
red1 = "#C8767D" # bright
green0 = "#D0796D"
green1 = "#DB9A91"
yellow0 = "#C6846C"
yellow1 = "#D4A391"
blue0 = "#938579"
blue1 = "#AFA49B"
purple0 = "#877B85"
purple1 = "#877B85"
aqua0 = "#7eb5ed"
aqua1 = "#87c3ff"
orange0 = "#e37b3e"
orange1 = "#f78644"
